DROP TABLE IF EXISTS RESTAURANT;
CREATE TABLE RESTAURANT (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
peanutScore INT(5) NOT NULL,
eggScore INT(5) NOT NULL,
dairyScore INT(5) NOT NULL,
overallScore INT(15) NOT NULL
);